### ISSUE TITLE
Can't run the say-hello (errors starting)

### ISSUE THREAD

**Issue by mgamache** [freshworks-developers/say-hello#10]
I am seeing the following errors when running the say-hello app:

Minor Node.js mistmatch. App was developed in 18.18.2 and is being run in v18.20.4.
Node.js version in manfiest is being updated to the current version.
The local server could not be started due to the following issue(s):
✖ type domain/api_key is not valid from platform version 3.0. Please use type 'text' in freshdesk_subdomain field
✖ type domain/api_key is not valid from platform version 3.0. Please use type 'text' in freshdesk_api_key field
✖ Found unsupported key 'type_attributes' in freshdesk_subdomain. type_attributes is not supported from platform version 3.0
✖ Found unsupported key 'type_attributes' in freshdesk_api_key. type_attributes is not supported from platform version 3.0
✖ Global apps support is not enabled for the current app. Please run `fdk config set global_apps.enabled true` to enable support.

**Comment by Sri-vidhya-SS** [comment]
Hi @mgamache , thanks for flagging this issue. We have fixed it, feel free to test this out when you can.
